language: node_js

node_js:
  - '0.10'
  - '0.11'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm install
  - bower install
  - grunt test

deploy:
  provider: heroku
  all_branches: true
  api_key:
    secure: j4VrKwDJetYtYLRBBSbnPXtOsg82yPOVKRCkopbQShoY0OIb7PIGzg0BvrEHHEmQceQEGQFLRm9ru/igmACjgscKzHBtVMxRt5a2AUP923CrS5cNRJbnyoMg0aFn3k0yAZyzXB9xkFsAXmnPNAfXMqG9W2QKLxXS03yLqzSL//s=
  app: ng-carousel
  on:
    repo: Wildhoney/ngRoundabout
